apiVersion: 1

datasources:
  - name: FlowSense Prometheus
    type: prometheus
    uid: flowsense-prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
